python intermimic/run.py \
--task InterMimic \
--cfg_env intermimic/data/cfg/omomo_train.yaml \
--cfg_train intermimic/data/cfg/train/rlg/omomo.yaml \
--motion_file InterAct/Parahome_s10_move_kettle \
--dataSub sub10 \
--output checkpoints \
--robotType s10.xml \
# --headless \
