python intermimic/run.py \
--seed 2025 \
--task InterMimic \
--cfg_env intermimic/data/cfg/omomo_train.yaml \
--cfg_train intermimic/data/cfg/train/rlg/omomo.yaml \
--motion_file InterAct/int_s110_cupdrink \
--exp_name S27_int_s110_cupdrink \
--dataSub sub110 \
--output checkpoints \
--robotType s110.xml \
--headless \
