python intermimic/run.py \
--task InterMimic \
--cfg_env intermimic/data/cfg/omomo_train.yaml \
--cfg_train intermimic/data/cfg/train/rlg/omomo.yaml \
--motion_file InterAct/Parahome_s6_place_book \
--dataSub sub6 \
--output checkpoints \
--robotType s6.xml \
--exp_name Parahome_s6_place_book \
# --headless \
